version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_USER: gokhan
      POSTGRES_PORT: 5432
      POSTGRES_DB: gokhan
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_ADVERTISED_HOST_NAME: zookeeper
  redis:
    image: redis
    ports:
      - "6379:6379"
