swagger: "2.0"
info:
  description: Todo Api Hold Info
  version: 1.0.0
  title: TODO API
  contact:
    email: gkkocer@gmail.com
schemes:
  - "https"
  - "http"
tags:
  - name: todo
    description: Todo Related
paths:
  /todos/{todo_id}:
    parameters:
      - name: todo_id
        in: path
        description: Todo ID
        type: integer
        format: int64
        required: true
    get:
      tags:
        - Todo
      summary: get todo with id
      operationId: getTodo
      description: get todo with ID
      produces:
        - application/json     
      responses:
        "200":
          description: Todo is successfully returned
          schema:
            $ref: "#/definitions/TodoResponse"
        "400":
          description: Bad request
    delete:
      tags:
        - todo
      operationId: deleteTodo
      security:
        - Bearer: []
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        "204":
          description: Todo deleted
        "400":
          description: Bad Request
        "404":
          description: Todo Not Found
        "500":
          description: Internal Server Error
definitions:
  TodoResponse:
    type: object
    properties:
      id:
        type: integer
        format: uint64
      description:
        type: string
      status:
        type: string
  PostTodoRequest:
    type: object
    properties:
      description:
        type: string
      status:
        type: string