BEGIN;

CREATE TABLE todos (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "status" varchar(32) NOT NULL DEFAULT 'ACTIVE',
  "description" varchar(128) NOT NULL,   
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()), 
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "deleted_at"   TIMESTAMPTZ
);
COMMIT;