BEGIN;

CREATE TABLE todos (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "status" varchar(32) NOT NULL DEFAULT 'ACTIVE',
  "description" varchar(128) NOT NULL,   
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()), 
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "deleted_at"   TIMESTAMPTZ
  
);
COMMIT;

CREATE TABLE users (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "name" varchar(32) NOT NULL DEFAULT 'ACTIVE',
  "email" varchar(32) NOT NULL,   
  "password"  NOT NULL , 
  "created_at"  NOT NULL,
  "updated_at"  NOT NULL,
  "deleted_at"  NOT NULL
);
COMMIT;